
os:
  - Visual Studio 2013
  - Visual Studio 2015

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - mkdir deps
  - cd deps
  # libSDL
  - curl -fsSL -o libsdl.zip https://libsdl.org/release/SDL-devel-1.2.15-VC.zip
  - 7z x libsdl.zip
  # libSDL_gfx expects libs at a certain place
  - mkdir SDL-1.2.15\VisualC\Debug
  - copy SDL-1.2.15\lib\x86\* SDL-1.2.15\VisualC\Debug
  - copy SDL-1.2.15 libsdl
  # libSDL_gfx
  - curl -fsSL -o libsdl_gfx.tar.gz http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.26.tar.gz
  - 7z x libsdl_gfx.tar.gz -so | 7z x -si -ttar > nul
  - move SDL_gfx-2.0.26 libsdl_gfx
  - cd libsdl_gfx
  - msbuild SDL_gfx_VS2015.sln
  - cd ..
  # go back to source root
  - cd ..


build_script:
  - mkdir build
  - cd build 
  - cmake .. -DSDL_INCLUDE_DIR=..\deps\libsdl\include -DSDL_LIBRARY=..\deps\libsdl\lib\x64\SDL.lib -DSDLGFX_INCLUDE_DIR=..\deps\libsdl_gfx -DSDLGFX_LIBRARY=..\deps\libsdl_gfx\Debug\SDL_gfx.lib
  - cmake --build .

