
os:
  - Visual Studio 2019

install:
  - mkdir deps
  - cd deps
  # libSDL
  - curl -fsSL -o libsdl.zip https://libsdl.org/release/SDL-devel-1.2.15-VC.zip
  - 7z x libsdl.zip
  - move SDL-1.2.15 libsdl
  # libSDL_gfx
  - curl -fsSL -o libsdl_gfx.tar.gz http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.26.tar.gz
  - 7z x libsdl_gfx.tar.gz -so | 7z x -si -ttar > nul
  - move SDL_gfx-2.0.26 libsdl_gfx
  # go back to source root
  - cd ..


build_script:
  - mkdir build
  - cd build 
  - cmake .. -A Win32 -DSDL_INCLUDE_DIR=..\deps\libsdl\include -DSDL_LIBRARY=..\src\msw\SDL.lib -DSDLMAIN_LIBRARY=..\src\msw\SDLmain.lib -DSDL_GFX_INCLUDE_DIRS=..\deps\libsdl_gfx -DSDL_GFX_LIBRARIES=..\src\msw\SDL_gfx.lib
  - cmake --build .
  # test packaging as well
  - cmake --build . --config Release
  - cpack

