language: c
dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]
  then
     sudo apt-get install libsdl-gfx1.2-dev
  fi
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]
  then
     brew install sdl_gfx
  fi



# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

