language: c
dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]
  then
     sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev
  fi


# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

