#!/bin/sh
#
# simple script for building releases
#
 
SRCDIR=../src
DSTDIR=linux

VER=`grep "define VERSION"  ../src/main.c | awk '{print $3}' | sed s/\"//g`

###

# make it look for libs in own dir
export LD_RUN_PATH=.

make -C $SRCDIR clean
make -C $SRCDIR 

strip $SRCDIR/omron++

rm -rf $DSTDIR/*
mkdir -p $DSTDIR

cp $SRCDIR/omron++ $DSTDIR
cp $SRCDIR/README $DSTDIR
cp $SRCDIR/README-SDL $DSTDIR
cp $SRCDIR/NEWS $DSTDIR
cp $SRCDIR/*.xpm $DSTDIR
cp /usr/lib/libSDL-1.2.so.0 $DSTDIR
cp /usr/lib/libSDL_gfx.so.4 $DSTDIR

cd $DSTDIR
mkdir omron++_$VER 
mv * omron++_$VER
tar cfz omron++_$VER-linux_i386.tar.gz omron++_$VER





