#!/bin/sh
#
# simple script for building releases
#
 
SRCDIR=src
DSTDIR=releases/linux

VER=`grep "define VERSION"  ../src/main.c | awk '{print $3}' | sed s/\"//g`

###

# make it look for libs in own dir
export LD_RUN_PATH=.

cd ..

make distclean

./autogen.sh

make clean

make 

strip $SRCDIR/omron++

rm -rf $DSTDIR/*
mkdir -p $DSTDIR

cp $SRCDIR/omron++ $DSTDIR
cp README $DSTDIR
cp README-SDL $DSTDIR
cp NEWS $DSTDIR
cp $SRCDIR/*.xpm $DSTDIR
cp /usr/lib/libSDL-1.2.so.0 $DSTDIR


cd $DSTDIR
mkdir omron++_$VER 
mv * omron++_$VER
tar cfz omron++_$VER-linux_i386.tar.gz omron++_$VER





