#!/bin/sh
#
# simple script for building releases
#
 
SRCDIR=src
DSTDIR=releases/osx

VER=`grep "define VERSION"  ../src/main.c | awk '{print $3}' | sed s/\"//g`

#######
 

cd ..

./autogen.sh

make clean

make appbundle

mkdir -p $DSTDIR
mv $SRCDIR/Omron++.app $DSTDIR

cd $DSTDIR                                                                      
zip -r omron++_$VER-osx.zip Omron++.app
