#!/bin/sh
#
# this is just quick'n'dirty and will probably not work on your system ...
#
# 

SRCDIR=src
DSTDIR=releases/win32


VER=`grep "define VERSION"  ../src/main.c | awk '{print $3}' | sed s/\"//g`  

cd ..

echo clean...
rm -rf $DSTDIR/*
make clean


echo compile...
./autogen.sh --build=x86_64-unknown-linux-gnu --host=i586-mingw32msvc --with-sdl-config=/usr/local/share/win32-cross-env/bin/sdl-config 
make -C $SRCDIR

echo copy...
mkdir -p $DSTDIR
cp $SRCDIR/omron++.exe  $DSTDIR
i586-mingw32msvc-strip $DSTDIR/omron++.exe
cp /usr/local/share/win32-cross-env/lib/SDL.dll $DSTDIR
cp /usr/local/share/win32-cross-env/lib/SDL_gfx.dll $DSTDIR
cp README $DSTDIR/README.TXT
unix2dos $DSTDIR/README.TXT
cp README-SDL $DSTDIR/README-SDL.TXT
unix2dos $DSTDIR/README-SDL.TXT
cp NEWS $DSTDIR/NEWS.TXT
unix2dos $DSTDIR/NEWS.TXT

echo zip...
cd $DSTDIR
zip omron++_$VER-win32.zip omron++.exe *.TXT *.dll
